name: "Irrigation Advisor (Simple)"
version: "1.0.1"
slug: "irrigation_advisor_simple"  
description: "Simple irrigation advisor with weather data"
url: "https://github.com/yourusername/irrigation-advisor"
arch:
  - amd64
  - armv7
  - aarch64
init: false
startup: services
options:
  api_key: ""
  latitude: 46.65
  longitude: 20.14
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
schema:
  api_key: "str"
  latitude: "float"
  longitude: "float" 
  mqtt_broker: "str"
  mqtt_port: "port"
  mqtt_username: "str?"
  mqtt_password: "str?"
services:
  - "mqtt:want"
ports:
  8099/tcp: null
map:
  - "share:rw"
