name: "Irrigation Advisor"
version: "2.1.20250828_2123"
slug: "irrigation_advisor"  
description: "Simple irrigation advisor with automatic scheduler and timestamped logging"
url: "https://github.com/vinczem/irrigation-advisor"
arch:
  - amd64
  - armv7
  - aarch64
init: false
startup: services
options:
  api_key: ""
  latitude: 46.65
  longitude: 20.14
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  enable_auto_check: true
  check_interval_minutes: 30
  log_level: "info"
schema:
  api_key: "str"
  latitude: "float"
  longitude: "float" 
  mqtt_broker: "str"
  mqtt_port: "port"
  mqtt_username: "str?"
  mqtt_password: "str?"
  enable_auto_check: "bool"
  check_interval_minutes: "int(1,1440)"  # 1 minutes to 24 hours
  log_level: "list(debug|info|warning|error)"
services:
  - "mqtt:want"
ports:
  8099/tcp: null
map:
  - "share:rw"
